### ISSUE TITLE
Re-running same script is failing

### ISSUE THREAD

**Issue by ajaychoudhary-bcg** [OctopusDeployLabs/SpaceCloner#13]
Re-running same script failing.
 "ErrorMessage": "A package reference with the ID 'ca503692-1e2e-453c-a1b0-ed7adecf5aeb' already exists"
 are we doing any check if things are already available then don't create?

**Comment by OctopusBob** [comment]
Please send your logs over to advice@octopus.com and we will take a look!

**Comment by OctopusBob** [comment]
Fixed in v2.0.1: https://github.com/OctopusDeployLabs/SpaceCloner/releases/tag/v2.0.1
