### ISSUE TITLE
Join-Path : A positional parameter cannot be found that accepts argument 'Core'.

### ISSUE THREAD

**Issue by DevOpsDerek** [OctopusDeployLabs/SpaceCloner#9]
When trying to execute CloneSpaceProject.ps1, it errors with the below: 

Join-Path : A positional parameter cannot be found that accepts argument 'Core'.
At C:\Users\derek\Downloads\SpaceCloner-1.8.2\CloneSpaceProject.ps1:27 char:4
+ . (Join-Path $PSScriptRoot "src" "Core" "Logging.ps1")
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
    
Command run with values changed

.\CloneSpaceProject.ps1 -SourceOctopusUrl "URLOFSPACE" `
    -SourceOctopusApiKey "SECUREAPIKEY" `
    -SourceSpaceName "SpaceName `
    -DestinationOctopusUrl "DestinationURL" `
    -DestinationOctopusApiKey "SECUREAPIKEY" `
    -DestinationSpaceName "Default" `    
    -ProjectsToClone "all"

This issue has been confirmed by additional users.

**Comment by OctopusBob** [comment]
This will be fixed in release 2.0.0 (https://github.com/OctopusDeployLabs/SpaceCloner/releases/tag/v2.0.0-rc1)
